{% set name = "ciocheck" %}
{% set version = "0.1.1" %}
{% set hash = "03d02a7c5348e2d040e8e229254d447ef51f2076cfb8153d4b25f32ea3915488" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/ContinuumIO/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 3
  entry_points:
    - ciocheck = ciocheck.main:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - autopep8
    - coverage
    - flake8
    - isort
    - pydocstyle
    - pylint
    - pytest
    - pytest-cov
    - pytest-json
    - pytest-xdist
    - python >={{ python_min }}
    - six
    - yapf

test:
  requires:
    - python {{ python_min }}
  imports:
    - ciocheck

about:
  home: https://github.com/ContinuumIO/ciocheck
  summary: "Continuum Analytics linter/formater/tester helper"
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/ContinuumIO/ciocheck

extra:
  recipe-maintainers:
    - goanpeca
