travis:
  secure:
    BINSTAR_TOKEN: m6pTVbqVHwzAP579/bjtezykPkILEvbyzM2q85EPopTql7J6KaUVMRmYHYKmkl/QfAGzKE+v7NhicOYgu0vZh8fKdo7erxELml3mwNCMTjYdtepAqrQr/VDJONTGNTHZCsp2dujsGvefm1RvfcFhKO8LZ6/6FE/YfjeSABlf5v/rhWmLKgWu84eTHwoYeCzNqzQ/UrkmIJZhgxXs+NrnJJwFSlSiziZstgJJp1GdJbwJ9FHk+EpOPg5ros5SiCMEAnUsfauc4Kf4Xj3K4AJAOT67s6+zgO9DpVc029DNYl8Xbf5CY+hG+M6fsLMKlRrZczdNHWr9v2A2AB7L2hcOBorMbazd9kI9VMZOuIwFV7t/kM8O2GRkoJlYlEEN73fSqSUUkKH1JCrj38yogZTvXkec+ZtHjjhIrZjofLN/7MuDLA8mdCB0uMy1bLmZvneK6D2zracqJymevOWQdRBr11Yb8OyT0b0wKppEXswVqTW3zCWcJ1KAUu/lGs79zQS6oiHeiqTfrVUpGT06M2lfp3++/okyti6Dr7msBAChIgpvFZZnCD6ZXy69/gBf4ecbgb6Iy4iIKmYNqd/xUokj5d8MSNlwD/S1nqX2EGlaGVFm5AMWhDmPQSJUkCRj7NdK7xUWhPUryp/+RYqWjkVg1v8XpWNHf108KDYSQtOSpmc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
